# Generated by Django 4.2.3 on 2023-07-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, null=None, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
